###
GET http://localhost:3000/api/v1/user HTTP/1.1

###
POST http://localhost:3000/api/v1/user HTTP/1.1
Content-Type: application/json

{
  "name": "Oscar",
  "email": "oscar@email.com",
  "password": "Oscar123"
}

###
POST http://localhost:3000/api/v1/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "efrain@email.com",
  "password": "efrain123"
}

###
GET http://localhost:3000/api/v1/user/65693ce69ea981d62faa2d42 HTTP/1.1